SELECT TOP (1000) [employee_id]
      ,[age]
      ,[gender]
      ,[years_at_company]
      ,[job_role]
      ,[monthly_income]
      ,[work_life_balance]
      ,[job_satisfaction]
      ,[performance_rating]
      ,[number_of_promotions]
      ,[overtime]
      ,[distance_from_home]
      ,[education_level]
      ,[marital_status]
      ,[number_of_dependents]
      ,[job_level]
      ,[company_size]
      ,[company_tenure_in_months]
      ,[remote_work]
      ,[leadership_opportunities]
      ,[innovation_opportunities]
      ,[company_reputation]
      ,[employee_recognition]
      ,[attrition]
  FROM [Employees_Processed].[dbo].[Employees_Processed]
