ROW_KEYS = [
    "employee_id",
    "age",
    "gender",
    "years_at_company",
    "job_role",
    "monthly_income",
    "work_life_balance",
    "job_satisfaction",
    "performance_rating",
    "number_of_promotions",
    "overtime",
    "distance_from_home",
    "education_level",
    "marital_status",
    "number_of_dependents",
    "job_level",
    "company_size",
    "company_tenure_in_months",
    "remote_work",
    "leadership_opportunities",
    "innovation_opportunities",
    "company_reputation",
    "employee_recognition",
    "attrition",
]

ROWS_SCHEMA = {
    "type": "array",
    "items": {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "employee_id": {"type": ["integer", "null"]},
            "age": {"type": ["integer", "null"]},
            "gender": {"type": ["string", "null"]},
            "years_at_company": {"type": ["integer", "null"]},
            "job_role": {"type": ["string", "null"]},
            "monthly_income": {"type": ["integer", "null"]},
            "work_life_balance": {"type": ["string", "null"]},
            "job_satisfaction": {"type": ["string", "null"]},
            "performance_rating": {"type": ["string", "null"]},
            "number_of_promotions": {"type": ["integer", "null"]},
            "overtime": {"type": ["string", "null"]},
            "distance_from_home": {"type": ["integer", "null"]},
            "education_level": {"type": ["string", "null"]},
            "marital_status": {"type": ["string", "null"]},
            "number_of_dependents": {"type": ["integer", "null"]},
            "job_level": {"type": ["string", "null"]},
            "company_size": {"type": ["string", "null"]},
            "company_tenure_in_months": {"type": ["integer", "null"]},
            "remote_work": {"type": ["string", "null"]},
            "leadership_opportunities": {"type": ["string", "null"]},
            "innovation_opportunities": {"type": ["string", "null"]},
            "company_reputation": {"type": ["string", "null"]},
            "employee_recognition": {"type": ["string", "null"]},
            "attrition": {"type": ["string", "null"]},
        },
        "required": ROW_KEYS,
    },
}
